
AM qualifications

* if openstax instructor account:
* some instructors have to apply (might be a delay)


/edx/app/edxapp/edx-platform/cms/djangoapps/openstax_integrator/salesforce
/edx/app/edxapp/edx-platform/cms/djangoapps/openstax_integrator/salesforce/management/commands

CampaignId: 7010m0000002pARAAY

{u'CampaignID': u'7010m0000002pARAAY',
  u'Completed_Assignment_date__c': None,
  u'Completed_Training_Wheels_date__c': None,
  u'ContactID': u'0030m00000JcBaJAAV',
  u'Estimated_Enrollment__c': None,
  u'Initial_Sign_in_Date__c': '2019-02-15',
  u'Most_recent_sign_in_date__c': '2019-02-15',
  u'Soft_Ask_Decision__c': None,
  u'Soft_Ask_Decision_date__c': None,
  u'Started_Assignment_date__c': None,
  u'Status': 'Sent',
  u'accounts_uuid__c': u'0030m00000JcBaJAAV',
  u'latest_adoption_decision__c': None}

  [{u'extendedErrorDetails': None,
    u'fields': [u'ContactId'],
    u'message': u'Unable to create/update fields: ContactId. Please check the security settings of this field and verify that it is read/write for your profile or permission set.',
    u'statusCode': u'INVALID_FIELD_FOR_INSERT_UPDATE'}]
  [{u'extendedErrorDetails': None,
    u'fields': [u'ContactId'],
    u'message': u'Unable to create/update fields: ContactId. Please check the security settings of this field and verify that it is read/write for your profile or permission set.',
    u'statusCode': u'INVALID_FIELD_FOR_INSERT_UPDATE'}]
  [{u'extendedErrorDetails': None,
    u'fields': [],
    u'message': u'Already a campaign member.',
    u'statusCode': u'DUPLICATE_VALUE'}]


https://support.veeva.com/hc/en-us/articles/115000100033-Error-Field-name-provided-does-not-match-an-External-ID-Salesforce-Id-or-Indexed-field-During-Network-Subscription-Failure

Overview:
=============
Network subscription fails with the following error:
Field name provided, [SFDC Field Name] does not match an External ID, Salesforce Id, or Indexed field for [SFDC Object Name].

Root Cause:
=============
Network Object Mapping records include the External ID API Name field to specify the External Id field to be used when performing the Upserts during the Network Subscription. This field must be configured with the External Id attribute.

The Network Object Mapping edit page only allows fields with the External Id attribute to be selected. If these records are Data Loaded, incorrect fields may be populated.


Solution:
=============
The field specified in the External ID API Name field on the Network Object Mapping record for each object must be configured as an External ID field. The field mapping can be changed to a valid External Id field, or the mapped field can be set as an External Id.





[

{u'created': False,
  u'errors': [{u'extendedErrorDetails': None,
               u'fields': [u'ContactId'],
               u'message': u'Unable to create/update fields: ContactId. Please check the security settings of this field and verify that it is read/write for your profile or permission set.',
               u'statusCode': u'INVALID_FIELD_FOR_INSERT_UPDATE'}],
  u'id': None,
  u'success': False},

 {u'created': False,
  u'errors': [{u'extendedErrorDetails': None,
               u'fields': [u'ContactId'],
               u'message': u'Unable to create/update fields: ContactId. Please check the security settings of this field and verify that it is read/write for your profile or permission set.',
               u'statusCode': u'INVALID_FIELD_FOR_INSERT_UPDATE'}],
  u'id': None,
  u'success': False},

 {u'created': True,
  u'errors': [{u'extendedErrorDetails': None,
               u'fields': [],
               u'message': u'Already a campaign member.',
               u'statusCode': u'DUPLICATE_VALUE'}],
  u'id': None,
  u'success': False}

  ]
